spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/