spring:
  datasource:
    url: jdbc:postgresql://localhost:8844/keycloak_db
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:8844/keycloak_db
    user: keycloak
    password : password
    change-log: classpath:/db/changelog/master.xml
    default-schema: order_stock
    clear-checksums: true
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/innowise
  rabbitmq:
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8003

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

rabbitmq:
  exchange: productAvailability

cors:
  origins: "http://localhost:8002"
  headers: "*"
