spring:
  datasource:
    url: jdbc:postgresql://localhost:8844/keycloak_db
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/innowise
  rabbitmq:
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8004

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

rabbitmq:
  queue: check
  exchange: productAvailability
  routing-key: check