spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:8844/keycloak_db
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8002