server:
  port: 8000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uyutov/innowise
          username: Uyutov
          password: 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
          search-paths: order-stock-microservices/config-repo